<?php


namespace app\command;


use think\console\Command;
use think\console\Input;
use think\console\Output;
use think\Db;

class Test extends Command
{
    protected function configure()
    {
        //parent::configure(); // TODO: Change the autogenerated stub
        $this->setName("test");
           // ->addArgument()
    }
    protected function execute(Input $input, Output $output)
    {
        //parent::execute($input, $output); // TODO: Change the autogenerated stub
       /* $list = Db::name("member")->alias("m")
            ->distinct("m.id")
            ->field("m.id, m.level, m.oldlevel")
            ->leftJoin("groups g", "m.id=g.uid")
            ->where("m.level", ">",0)
            ->where("g.status", "in", [2, 3])
            ->count();*/

    }

}